services:
  database:
      build:
        context: .
        target: mysql
      container_name: mysql_db
      hostname: mysql_db
      ports:
          - 3309:3306
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_NAME}'
      volumes:
          - ./db:/var/lib/mysql
      networks:
        - connection
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${DB_PASSWORD}"]
        interval: 30s
        timeout: 10s
        retries: 5

  api:
    container_name: imitter_api
    build:
      context: .
      target: api
    volumes:
      - ./:/usr/api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
    networks:
        - connection
    depends_on:
      database:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  connection:
    name: connection




