services:
  api:
    build:
      context: .
      target: api
    volumes:
      - ./:/usr/api
    ports:
      - 8080:8080
    networks:
        - connection
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
      image: mysql:latest
      hostname: mysql_db
      ports:
          - 3309:3306
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_NAME}'
      volumes:
          - ./db:/var/lib/mysql
      networks:
        - connection

networks:
  connection:
    name: connection



