services:
  database:
      image: mysql:8.0.40-oracle
      container_name: mysql_db
      hostname: mysql_db
      ports:
          - 3309:3306
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_NAME}'
      volumes:
          - ./database/imitter_schema.sql:/docker-entrypoint-initdb.d/imitter_schema.sql
          - ./db_data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

      networks:
        - connection

  api:
    container_name: imitter_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
        - connection
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:

networks:
  connection:




